### ISSUE TITLE
Quick question on the latest commit

### ISSUE THREAD

**Issue by 1alessandro1** [khronokernel/What-s-new-in-macOS-Catalina#4]
Good evening, thanks a lot for your guides, they're very cool to read through, I learned a lot from them...

Something about the latest commit, could you please integrate the EC ssdt patch on "Getting Started with ACPI" also? 

It would be perfect to integrate many other guides which implement acpi modifications in order to clarify this topic, not quite easy even 1 year later my first installation.

For example it could be perfect if you're planning to implement ACPI fixes

-For native nvram management on Z390 and B360 (as described here https://www.hackintosh-forum.de/forum/thread/46154 and implemented later as an ssdt on opencore https://github.com/acidanthera/OpenCorePkg/commit/a825da4e566bba827f0c462d598eaa2b2f0b84f4)

-For Fixing EC on catalina (you already have it)
-Moving/mirroring the SSDT-PM/SSDT-USB which implement corpnewt tools

-ssdt rtc/awac guide with reference to Opencore's AcpiSamples section

-Maybe trackpad fixes/gpio pinning 

(I may have missed many other ssdt fixes but I tried to provide some examples on how to maintain that "Getting Started with ACPI" which may become a guide on its own)

I'm looking forward to knowing what's your opinion on this :-)

**Comment by khronokernel** [comment]
@1alessandro1 
Hmm, the OpenCore Vanilla Guide already goes over AWAC/RTC, EC, and PLUG as they're the main ones required for booting(PLUG excluded, I plan to add SSDT-PMC to the OC guide but keep forgetting). It would be easier for me to put more effort into expanding the guide than make a separate ACPI guide as there's far too many SSDTs to cover, plus I have no clue where to start with laptop patching. I'm mostly a desktop user. This EC guide was made because EC issues were super common and just wanted to make a more step-by-step guide for laptops on grabbing the DSDT, figure out the EC and patching it as the "What's new in Catalina" post was lacking. Also got tired of repeating myself ;p

I do love the idea of an all inclusive ACPI guide but we already have that for desktops in the OC guide, and for laptops ~~[Fewt's laptop guide](https://fewtarius.gitbook.io/laptopguide/) covers it all~~ checking it shows he goes into very basic patching but links to Rehabman for extended patching. Hmm, this would be a section to expand upon. I'd love to write some more deep dive guides on it, but no laptop hardware or experience. At least with AMD I've troubleshooted enough to know them but laptops are something I generally avoid.

If you have any other suggestions or like to clarify what you said before, I'm all ears but for now I'll be closing this issue. Though if you do message back, include `@khronokernel` as this will send an email. Otherwise I won't notice and forget about this thread
